# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemeHackChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MemeHackChallenge
	pod 'Alamofire'
	pod 'SnapKit'
	pod 'SwiftyJSON'

  target 'MemeHackChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemeHackChallengeUITests' do
    # Pods for testing
  end

end
